field: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
fieldLayouts:
  54740fa7-c999-46cf-ac6d-9d485820899c:
    tabs:
      -
        elements:
          -
            fieldUid: b026d20d-f781-469f-8c4c-5f5c65c66027 # Target
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: fa76440e-c84c-4d11-b665-375f32514aaa # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 7d7cf5ed-7c41-4d49-ba86-cef811f69683 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 133bba22-df33-4432-a49f-198e9c071f22 # Display
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  7d7cf5ed-7c41-4d49-ba86-cef811f69683: # Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: color
    instructions: ''
    name: Color
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  133bba22-df33-4432-a49f-198e9c071f22: # Display
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: display
    instructions: ''
    name: Display
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Align left'
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Align right'
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  b026d20d-f781-469f-8c4c-5f5c65c66027: # Target
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: target
    instructions: ''
    name: Target
    searchable: true
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Select an entry'
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  fa76440e-c84c-4d11-b665-375f32514aaa: # Caption
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: 'Leave blank to show title of target'
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: button
name: Button
sortOrder: 6
