field: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
fieldLayouts:
  373cf894-e8e4-4405-8f2f-9cf8e9c07c32:
    tabs:
      -
        elements:
          -
            fieldUid: ec6b5c42-b633-4465-8f26-2d43d78befe8 # Asset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: eb61a6f2-9d63-4730-8ccf-daebb6ba0824 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 25c13312-e79c-4f00-b607-88fab9e35920 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  25c13312-e79c-4f00-b607-88fab9e35920: # __blank__
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showDescription
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: 'Show description'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  eb61a6f2-9d63-4730-8ccf-daebb6ba0824: # __blank__
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showTitle
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: 'Show title'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  ec6b5c42-b633-4465-8f26-2d43d78befe8: # Asset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: asset
    instructions: ''
    name: Asset
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - json
      defaultUploadLocationSource: 'volume:cbbf12d2-97db-4750-8f2d-ea5a5ca1f975' # Embeds
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: true
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:cbbf12d2-97db-4750-8f2d-ea5a5ca1f975' # Embeds
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: embed
name: Embed
sortOrder: 7
