field: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
fieldLayouts:
  34d4bac1-c414-452a-adfc-eb21c10b1fc4:
    tabs:
      -
        elements:
          -
            fieldUid: 25fbe2f8-c1c3-4e3e-8a39-0b06a6392428 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  25fbe2f8-c1c3-4e3e-8a39-0b06a6392428: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: gallery
name: Gallery
sortOrder: 4
