field: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
fieldLayouts:
  070f840f-c5bc-4bd3-ad32-c6a5d55d9e3c:
    tabs:
      -
        elements:
          -
            fieldUid: c7d0c14f-5533-4bdc-863d-cedbbb544960 # __blank__
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            fieldUid: bad8f5ab-fcf4-4fec-9ade-7652b14f376e # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
fields:
  bad8f5ab-fcf4-4fec-9ade-7652b14f376e: # __blank__
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: tag
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - H2
            -
              - value
              - h2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - H3
            -
              - value
              - h3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H4
            -
              - value
              - h4
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  c7d0c14f-5533-4bdc-863d-cedbbb544960: # __blank__
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: __blank__
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 1
