field: ae7d91c8-8743-46bb-a954-438a27946b97 # Primary Navigation
fieldLayouts:
  28608963-de7b-4a84-8c8f-b35c82ae5c17:
    tabs:
      -
        elements:
          -
            fieldUid: 29984fa1-b01d-42e8-80e8-6983cc5a498c # Entries
            instructions: null
            label: null
            required: '1'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  29984fa1-b01d-42e8-80e8-6983cc5a498c: # Entries
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: ''
    name: Entries
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: topLevelLinks
name: 'Top Level Links'
sortOrder: 1
