fieldLayouts:
  fbe1d7ac-ee60-42f7-90eb-973bb5c52cf5:
    tabs:
      -
        elements:
          -
            heading: Header
            type: craft\fieldlayoutelements\Heading
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 9a302fae-a3bf-4298-8a06-24f8c8f6f335 # Featured Image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 3ef62a7b-6c6d-470f-88a6-31de5a099b38 # Teaser
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            heading: Content
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 58b2e318-26cc-47b8-bee2-81369731d72f # Body Content
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b218c14c-079e-4456-a770-37b2e4d7abdc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            heading: Relations
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: e4cf9f0d-54a6-4107-beac-daa51b8e5006 # Topics
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 6c2c7c89-c2ff-4ace-a3e6-aeddab27ab7b # Documents
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 9b2aaaa8-c827-4881-955a-86f2df0ea79c # Related Entries
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
        name: Content
        sortOrder: 1
handle: post
hasTitleField: true
name: Post
section: 0d69ffe4-360e-4d04-ac30-af0e4381b6ed # Post
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
