columnSuffix: null
contentColumnType: boolean
fieldGroup: 5d1e7a8c-bdb7-48c9-b9a8-9ab55c900868 # Users
handle: disableDraftHints
instructions: ''
name: 'Disable Draft Hints'
searchable: false
settings:
  default: false
  offLabel: 'No, i need them'
  onLabel: 'Yes, i''m tired of them'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
