columnSuffix: null
contentColumnType: string
fieldGroup: f1d8d989-2bc0-4a0f-b58f-a348276a5596 # Content
handle: teaser
instructions: ''
name: Teaser
searchable: true
settings:
  byteLimit: null
  charLimit: 60
  code: ''
  columnType: string
  initialRows: '4'
  multiline: ''
  placeholder: 'Short text'
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
