defaultPlacement: end
enableVersioning: true
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  97e0b749-86e3-49f1-918e-9b88758928f4: # English
    enabledByDefault: true
    hasUrls: true
    template: _sections/home
    uriFormat: __home__
  bbbb120d-5d71-4e7c-a164-487e401c4f2c: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _sections/home
    uriFormat: __home__
type: single
