defaultPlacement: end
enableVersioning: true
handle: post
name: Post
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
  -
    __assoc__:
      -
        - label
        - 'Post Index'
      -
        - urlFormat
        - '{% set e = craft.entries.section(''postIndex'').site(object.site).one %}{{e ? e.url : ''''}}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  97e0b749-86e3-49f1-918e-9b88758928f4: # English
    enabledByDefault: true
    hasUrls: true
    template: _sections/post
    uriFormat: 'post/{slug}'
  bbbb120d-5d71-4e7c-a164-487e401c4f2c: # Deutsch
    enabledByDefault: true
    hasUrls: true
    template: _sections/post
    uriFormat: 'beitrag/{slug}'
type: channel
